project_name: "Social Media Planner"
project_type: "web-app"
project_level: 2
output_folder: "docs"

bmm:
  workflow_status_file: "docs/bmm-workflow-status.yaml"
  sprint_status_file: "docs/sprint-status.yaml"

paths:
  docs: "docs"
  stories: "docs/stories"
  tests: "tests"
  src: "src"

user_name: "Sami"

# Project metadata
created_at: "2026-01-06"
bmad_version: "v6"
